// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0SPX1s5mngDguxyUlYyegPPy0Uoesah4',
    appId: '1:292902459955:web:3e7410fb1a10cb6dada146',
    messagingSenderId: '292902459955',
    projectId: 'web-app-moriah',
    authDomain: 'web-app-moriah.firebaseapp.com',
    storageBucket: 'web-app-moriah.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC1fY-hHuSRZl6I57tazmECrgrjM2t_JY',
    appId: '1:292902459955:android:2a42fb6796edd6dbada146',
    messagingSenderId: '292902459955',
    projectId: 'web-app-moriah',
    storageBucket: 'web-app-moriah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBirSHoQtHnyE5wAnSdtvrrx5oWhNwx5I8',
    appId: '1:292902459955:ios:cc9bc8a633936f98ada146',
    messagingSenderId: '292902459955',
    projectId: 'web-app-moriah',
    storageBucket: 'web-app-moriah.firebasestorage.app',
    iosBundleId: 'br.com.studiomoriah.moriahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBirSHoQtHnyE5wAnSdtvrrx5oWhNwx5I8',
    appId: '1:292902459955:ios:cc9bc8a633936f98ada146',
    messagingSenderId: '292902459955',
    projectId: 'web-app-moriah',
    storageBucket: 'web-app-moriah.firebasestorage.app',
    iosBundleId: 'br.com.studiomoriah.moriahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0SPX1s5mngDguxyUlYyegPPy0Uoesah4',
    appId: '1:292902459955:web:58c80db3f130aaa9ada146',
    messagingSenderId: '292902459955',
    projectId: 'web-app-moriah',
    authDomain: 'web-app-moriah.firebaseapp.com',
    storageBucket: 'web-app-moriah.firebasestorage.app',
  );
}
